export const AGENT_STATUSES = Object.freeze([
  'CREATED', 'INITIALIZING', 'READY', 'RUNNING', 'BLOCKED',
  'WAITING_RESOURCE', 'PAUSED', 'COMPLETED', 'FAILED', 'TERMINATED'
]);

export const TASK_STATUSES = Object.freeze([
  'PENDING', 'READY', 'RUNNING', 'BLOCKED', 'WAITING_RESOURCE',
  'REVIEW', 'COMPLETED', 'FAILED', 'CANCELLED'
]);

export const RESOURCE_STATUSES = Object.freeze([
  'AVAILABLE', 'LOW', 'DEGRADED', 'RATE_LIMITED', 'UNKNOWN', 'AUTH_REQUIRED', 'OFFLINE'
]);

export const EVENT_TYPES = Object.freeze([
  'TASK_CREATED', 'TASK_UPDATED', 'TASK_ASSIGNED', 'TASK_STARTED', 'TASK_BLOCKED',
  'TASK_COMPLETED', 'TASK_FAILED', 'TASK_CANCELLED', 'AGENT_CREATED', 'AGENT_READY',
  'AGENT_RATE_LIMITED', 'AGENT_RESUMED', 'AGENT_COMPLETED', 'DIRECTIVE_UPDATED',
  'ISSUE_CREATED', 'ISSUE_ASSIGNED', 'PR_CREATED', 'PR_APPROVED', 'CI_FAILED',
  'CI_PASSED', 'REVIEW_REQUIRED', 'GOD_DECISION_REQUIRED', 'CUSTOMER_DECISION_REQUIRED',
  'AGENT_STATUS_CHANGED', 'RESOURCE_STATUS_CHANGED', 'TASK_DISPATCHED', 'TASK_RESULT_RECORDED',
  'GOD_MESSAGE_RECEIVED', 'GOD_DECISION_RESOLVED', 'DECISION_CREATED'
]);

export const AGENT_TRANSITIONS = Object.freeze({
  CREATED: new Set(['INITIALIZING', 'TERMINATED']),
  INITIALIZING: new Set(['READY', 'FAILED', 'TERMINATED']),
  READY: new Set(['RUNNING', 'PAUSED', 'TERMINATED']),
  RUNNING: new Set(['BLOCKED', 'WAITING_RESOURCE', 'PAUSED', 'COMPLETED', 'FAILED', 'READY', 'TERMINATED']),
  BLOCKED: new Set(['READY', 'RUNNING', 'PAUSED', 'FAILED', 'TERMINATED']),
  WAITING_RESOURCE: new Set(['READY', 'RUNNING', 'PAUSED', 'FAILED', 'TERMINATED']),
  PAUSED: new Set(['READY', 'RUNNING', 'TERMINATED']),
  COMPLETED: new Set(['READY', 'TERMINATED']),
  FAILED: new Set(['READY', 'RUNNING', 'TERMINATED']),
  TERMINATED: new Set([])
});
